name: deops_pipeline_practice
on:
  workflow_dipatch:
    inputs:
      branch_name:
        required: true
        description: "provide the branch_name"
        type: choice
        options:
          - main
          - venky
      tag:
        description: "provide the tag"
        required: true
        type: environment
jobs:
  dev_job:
    name: dev job running
    run_on: ubuntu-latest
    step:
    - name: checkout code
      uses: actions/checkout@v4
    - name: build docker build 
      run: |
        echo "code build"
        docker build -t venky:latest .
        docker images
    

